version: '2.1'
orbs:
  flutter: circleci/flutter@1.1.0
jobs:
  test_iOS:
    macos:
      xcode: 13.3.1
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          flutter_version: 2.10.5
          app-dir: example
      - flutter/install_ios_pod:
          app-dir: example
#      # - flutter/install_ios_gem
      - run:
          command: flutter test
          working_directory: example
workflows:
  distribute:
    jobs:
      - test_iOS