version: '2.1'
orbs:
  flutter: circleci/flutter@1.1.0
  android: circleci/android@1.0.3
jobs:
  test_iOS:
    macos:
      xcode: 13.3.1
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          flutter_version: 2.10.5
          app-dir: example
      - flutter/install_ios_pod:
          app-dir: example
#      # - flutter/install_ios_gem
      - run:
          command: flutter test
          working_directory: example
  publish_package:
    macos:
      xcode: 13.3.1
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          flutter_version: 2.10.5
          app-dir: example
      - run:
          name: Install dart
          command: |
              brew tap dart-lang/dart
              brew install dart
      - run:
          name: setup pub login
          command: sh .circleci/pub_login.sh  
      - run:
          name: publish pub
          command: dart pub publish --dry-run     
  test_Android:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          flutter_version: 2.10.5
          app-dir: example
      - flutter/install_android_gradle:
          app-dir: example
      # - flutter/install_android_gem
      - run:
          command: flutter test
          working_directory: example
workflows:
  version: 2  
  test_iOS:
    jobs:  
      - test_iOS
  test_Android:
    jobs:
      - test_Android
  publish_plugin:
    jobs:  
      - test_iOS
      - test_Android
      - hold_for_publish:
          type: approval
          requires:
            - test_iOS
            - test_Android
          filters:
            branches:
                only: 
                  - /release-(.*)/
      - publish_package:
          requires:
            - hold_for_publish
          filters:
            branches:
                only: 
                  - /release-(.*)/
