version: 2
jobs:
  distribute:
    macos:
      xcode: 12.5.1
    steps:
    - run:
        command: |
          mkdir ~/development && cd $_
          if [ "$(uname)" == 'Darwin' ]; then
            curl -o flutter_sdk.zip https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.10.5-stable.zip
            unzip -qq flutter_sdk.zip
          elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
            curl -o flutter_sdk.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_2.10.5-stable.tar.xz
            tar xf flutter_sdk.tar.xz
          else
            echo "Your platform ($(uname -a)) is not supported."
            exit 1
          fi
          echo 'export PATH=~/development/flutter/bin:$PATH' >> $BASH_ENV
        name: Install Flutter SDK
    - run:
        command: flutter doctor
    - restore_cache:
        keys:
        - pub-.-{{ checksum "./example/pubspec.lock" }}-{{ arch }}
    - run:
        command: |
          cd example
          flutter pub get
        name: Install Dependencies
        working_directory: ./
    - save_cache:
        key: pub-.-{{ checksum "./example/pubspec.lock" }}-{{ arch }}
        paths:
        - ./example/.dart_tool
    - restore_cache:
        keys:
        - pod-v1-{{ checksum "./example/ios/Podfile.lock" }}
    - run:
        command: pod install
        name: Install Dependencies
        working_directory: ./example/ios
    - save_cache:
        key: pod-v1-{{ checksum "./example/ios/Podfile.lock" }}
        paths:
        - ./example/ios/Pods
    - restore_cache:
        keys:
        - bundle-v1-ios-{{ checksum "./example/ios/Gemfile.lock" }}
    - run:
        command: |
          bundle config set path ./example/vendor/bundle
          bundle install
        name: Install Dependencies
        working_directory: ./example/ios
    - save_cache:
        key: bundle-v1-ios-{{ checksum "./example/ios/Gemfile.lock" }}
        paths:
        - ./example/ios/vendor/bundle
    - run:
        # command: bundle exec fastlane distribute
        command: flutter test
        working_directory: example
workflows:
  distribute:
    jobs:
    - distribute
  version: 2