env:
  MAC_BK_AGENT: eng-prod-us-west-2-mac-arm-macos-build-medium
  ENG_BK_AGENT: eng-default
  FLUTTER_VERSION: 2.10.5

steps:
  - name: ':hammer: Build and test iOS'
    key: 'build-test-ios'
    commands:
      - . ~/.zshrc
      - rbenv local 2.7.6
      - brew tap leoafarias/fvm
      - brew install fvm
      - fvm install ${FLUTTER_VERSION}
      - fvm use ${FLUTTER_VERSION}
      - cd example
      - xcrun simctl boot "iPhone 14" || true
      - fvm flutter pub get
      - fvm flutter precache --ios
      - cd ios && pod install && cd -
      - fvm flutter test
      - fvm flutter test integration_test/app_test.dart
    agents: 
      queue: ${MAC_BK_AGENT}
    timeout_in_minutes: 25

  - name: ':hammer: Build and test Android'
    key: 'build-test-android'
    commands:
      - flutter pub get
      - flutter emulators --launch flutter_emulator
      - echo 'emulator launched'
      - cd example
      - flutter build apk --debug
      - flutter test integration_test/app_test.dart
    plugins:
      - docker#v5.6.0:
          image: matspfeiffer/flutter
          user: "root"
          mount-buildkite-agent: true
    agents: 
      queue: ${ENG_BK_AGENT}
    timeout_in_minutes: 25

  - block: ':whale: Hold for publish'
    key: 'hold-publish'
    prompt: 'Publish package?'
    depends_on:
      - 'build-test-android'
      - 'build-test-ios'