env:
  MAC_BK_AGENT: eng-prod-us-west-2-mac-arm-macos-build-medium
  ENG_BK_AGENT: eng-default
  FLUTTER_VERSION: 3.10.0
  ANDROID_SDK_ROOT: ~/Library/Android/sdk
  ANDROID_SDKMANAGER: ~/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager

steps:
  - name: ":git: Create git tag"
    key: tag
    commands:
      - . ~/.zshrc
      - yes N | rbenv install 2.7.6 || true
      - rbenv local 2.7.6
      - ./.buildkite/bin/update_versions.sh "${ANDROID_VERSION}" android/build.gradle "${IOS_VERSION}" ios/rokt_sdk.podspec "${VERSION}" pubspec.yaml
      - ./.buildkite/bin/update_changelog.sh CHANGELOG.md "${VERSION}" "${CHANGELOG}"
      - ./.buildkite/bin/create_tag.sh "${VERSION}"
    agents:
      queue: ${MAC_BK_AGENT}

  - name: ":hammer: Build and test iOS"
    depends_on: tag
    key: build-test-ios
    commands:
      - . ~/.zshrc
      - yes N | rbenv install 2.7.6 || true
      - rbenv local 2.7.6
      - git fetch --all --tags --force
      - git checkout "v${VERSION}"
      - brew tap leoafarias/fvm
      - brew install fvm
      - fvm install ${FLUTTER_VERSION}
      - yes | fvm use ${FLUTTER_VERSION}
      - cd example
      - bundle check || bundle install --path vendor/bundle
      - rbenv local 2.7.6
      - xcrun simctl boot "iPhone 15" || true
      - fvm flutter pub get
      - fvm flutter precache --ios
      - cd ios
      - rbenv local 2.7.6
      - bundle check || bundle install --path vendor/bundle
      - bundle exec pod install --verbose --repo-update
      - cd -
      - bundle exec fvm flutter test
      - bundle exec fvm flutter test integration_test/app_test.dart
    agents:
      queue: ${MAC_BK_AGENT}
    timeout_in_minutes: 25

  - name: ":hammer: Build and test Android"
    key: build-test-android
    depends_on: tag
    commands:
      - . ~/.zshrc
      - yes N | rbenv install 2.7.6 || true
      - rbenv local 2.7.6
      - git fetch --all --tags --force
      - git checkout "v${VERSION}"
      - brew tap leoafarias/fvm
      - brew install fvm
      - fvm install ${FLUTTER_VERSION}
      - yes | fvm use ${FLUTTER_VERSION}
      - xcrun simctl shutdown "iPhone 15" || true
      - fvm flutter config --android-sdk ${ANDROID_SDK_ROOT}
      - yes | ${ANDROID_SDKMANAGER} 'system-images;android-29;google_apis;arm64-v8a' 'platforms;android-29'
      - yes | ${ANDROID_SDKMANAGER} --licenses
      - echo no | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/avdmanager create avd --force -n flutter -k 'system-images;android-29;google_apis;arm64-v8a'
      - ${ANDROID_SDK_ROOT}/emulator/emulator -avd "flutter" -gpu swiftshader_indirect -noaudio -no-boot-anim -netdelay none -accel on -no-window -no-snapshot -memory 4096 -partition-size 4096 &
      - sleep 60
      - cd example && fvm flutter pub get
      - fvm flutter build apk --debug
      - fvm flutter test integration_test/app_test.dart
    agents:
      queue: ${MAC_BK_AGENT}
    timeout_in_minutes: 25

  - name: ":rocket: Publish package"
    depends_on:
      - build-test-android
      - build-test-ios
    commands:
      - . ~/.zshrc
      - yes N | rbenv install 2.7.6 || true
      - rbenv local 2.7.6
      - git fetch --all --tags --force
      - git checkout "v${VERSION}"
      - brew tap leoafarias/fvm
      - brew install fvm
      - fvm install ${FLUTTER_VERSION}
      - yes | fvm use ${FLUTTER_VERSION}
      - cd example && fvm flutter pub get && cd -
      - brew tap dart-lang/dart
      - brew install dart
      - sh .buildkite/pub_login.sh
      - fvm dart pub publish -f
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          region: us-west-2
          env:
            PUB_DEV_PUBLISH_ACCESS_TOKEN:
              secret-id: stage-flutter-sdk-buildkite
              json-key: .PUB_DEV_PUBLISH_ACCESS_TOKEN
            PUB_DEV_PUBLISH_REFRESH_TOKEN:
              secret-id: stage-flutter-sdk-buildkite
              json-key: .PUB_DEV_PUBLISH_REFRESH_TOKEN
            PUB_DEV_PUBLISH_TOKEN_ENDPOINT:
              secret-id: stage-flutter-sdk-buildkite
              json-key: .PUB_DEV_PUBLISH_TOKEN_ENDPOINT
            PUB_DEV_PUBLISH_EXPIRATION:
              secret-id: stage-flutter-sdk-buildkite
              json-key: .PUB_DEV_PUBLISH_EXPIRATION
    agents:
      queue: ${MAC_BK_AGENT}
    timeout_in_minutes: 25
