name: Create draft release

on:
  workflow_dispatch: # checkov:skip=CKV_GHA_7
    inputs:
      bump-type:
        description: Specify if the version should be bumped as major, minor, patch
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  publish-draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Get current version
        id: version-file
        run: |
          version_from_file=$(head -n 1 VERSION)
          echo "release-version=$version_from_file" >> $GITHUB_OUTPUT
      - name: Bump version
        id: bump-version
        uses: actions-ecosystem/action-bump-semver@34e334551143a5301f38c830e44a22273c6ff5c5 # v1.0.0
        with:
          current_version: ${{ steps.version-file.outputs.release-version }}
          level: ${{ github.event.inputs.bump-type || 'patch' }}
      - name: Save validated version to file
        run: |
          echo "${{ steps.bump-version.outputs.new_version }}" > VERSION
      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@f62c3c390716df5af712ba5d94f4f4a8efc1306d # v3.1.0
        with:
          tag: ${{ steps.bump-version.outputs.new_version }}

      - name: Update pubspec.yaml
        run: |
          sed -i '' 's/version: .*/version: ${{ steps.bump-version.outputs.new_version }}/' pubspec.yaml

      - name: Setup Flutter
        uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046 #2.19.0
        with:
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Run dry-run publish
        run: |
          flutter pub publish --dry-run

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          commit-message: "Prepare release ${{ steps.bump-version.outputs.new_version }}"
          branch: release/${{ steps.bump-version.outputs.new_version }}
          title: "Prepare release ${{ steps.bump-version.outputs.new_version }}"
          base: main
          body: |
            Preparing for release ${{ steps.bump-version.outputs.new_version }}
            - Updated pubspec.yaml to new version
            - Updated CHANGELOG.md
            - Updated VERSION file
            - Ran a dry-run publish
          labels: |
            release
