name: Test iOS

on:
  workflow_call:
    inputs:
      flutter-version:
        required: false
        type: string
        default: 3.19.0
      ruby-version:
        required: false
        type: string
        default: 3.1.2
      xcode-version:
        required: false
        type: string
        default: "26.3"

permissions:
  contents: read

jobs:
  test_ios:
    runs-on: macos-15
    timeout-minutes: 30
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/example/Gemfile
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b #v1.321.0
        with:
          ruby-version: ${{ inputs.ruby-version }}
          bundler-cache: true
          rubygems: latest
          working-directory: example

      - name: Setup Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 #2.23.0
        with:
          flutter-version: ${{ inputs.flutter-version }}
          channel: stable
          cache: true

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 #v1.7.0
        with:
          xcode-version: ${{ inputs.xcode-version }}

      - name: Warm up CoreSimulator
        run: xcrun simctl list devices available

      - name: Get all packages Flutter
        working-directory: example
        run: |
          flutter pub get
          flutter precache --ios

      - name: Install iOS Dependencies
        working-directory: example/ios
        run: bundle exec pod install --verbose

      - uses: futureware-tech/simulator-action@e89aa8f93d3aec35083ff49d2854d07f7186f7f5 #v5
        id: simulator
        with:
          model: iPhone 17 Pro
          os_version: "26.2"
          wait_for_boot: true
          erase_before_boot: false

      - name: Run Flutter Tests (iOS)
        working-directory: example
        run: bundle exec flutter test

      - name: Run Flutter Integration Tests (iOS)
        working-directory: example
        env:
          SIMULATOR: ${{ steps.simulator.outputs.udid }}
        run: bundle exec flutter test integration_test/app_test.dart -d "$SIMULATOR" --dart-define=CI=true
